apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-runbook-vbscript
  namespace: openshift-monitoring
spec:
  groups:
  - name: test-runbook-sanitization
    interval: 30s
    rules:
    - alert: TestAlertVBScript
      expr: vector(1)
      for: 0m
      labels:
        severity: warning
        test: runbook-sanitization
        runbook_url: "vbscript:msgbox(1)"
      annotations:
        runbook_url: "vbscript:msgbox(1)"
        summary: "vbscript:msgbox(1)"
        description: "vbscript:msgbox(1)"