default_rollback: 3

entries:
  - project: perses-operator
    branch: release-coo-1.5
    component: perses-operator-1-5
    rollback: 3

  - project: monitoring-plugin
    branch: release-coo-ocp-4.15
    component: monitoring-console-plugin-pf5-1-5
    rollback: 2

  - project: monitoring-plugin
    branch: release-coo-ocp-4.19
    component: monitoring-console-plugin-pf6-1-5
    rollback: 2

  - project: monitoring-plugin
    branch: release-coo-ocp-4.22
    component: monitoring-console-plugin-1-5
    rollback: 2

  - project: logging-view-plugin
    branch: release-coo-ocp-4.12
    component: logging-console-plugin-pf4-1-5
    rollback: 2

  - project: logging-view-plugin
    branch: release-coo-ocp-4.15
    component: logging-console-plugin-pf5-1-5
    rollback: 2

  - project: logging-view-plugin
    branch: release-coo-ocp-4.22
    component: logging-console-plugin-1-5
    rollback: 2

  - project: distributed-tracing-plugin
    branch: release-coo-ocp-4.12
    component: distributed-tracing-console-plugin-pf4-1-5
    rollback: 2

  - project: distributed-tracing-plugin
    branch: release-coo-ocp-4.15
    component: distributed-tracing-console-plugin-pf5-1-5
    rollback: 2

  - project: distributed-tracing-plugin
    branch: release-coo-ocp-4.19
    component: distributed-tracing-console-plugin-pf6-1-5
    rollback: 2

  - project: distributed-tracing-plugin
    branch: release-coo-ocp-4.22
    component: distributed-tracing-console-plugin-1-5
    rollback: 2

  - project: troubleshooting-panel-plugin
    branch: release-coo-ocp-4.19
    component: troubleshooting-panel-console-plugin-pf6-1-5
    rollback: 2

  - project: troubleshooting-panel-plugin
    branch: release-coo-ocp-4.22
    component: troubleshooting-panel-console-plugin-1-5
    rollback: 2
